# Generated by Django 5.1.6 on 2025-03-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGreenHouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invernadero',
            name='imagen',
            field=models.ImageField(default='assets/Untitled.png', upload_to='assets/'),
        ),
    ]
