# Generated by Django 5.1.6 on 2025-03-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGreenHouse', '0002_invernadero_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invernadero',
            name='imagen',
            field=models.ImageField(default='./assets/default.jpg', upload_to='./assets/'),
        ),
    ]
